/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BreadCrumbs: typeof import('./src/components/BreadCrumbs.vue')['default']
    CardItem: typeof import('./src/components/CardItem.vue')['default']
    GridLayout: typeof import('./src/components/GridLayout.vue')['default']
    ParallaxItem: typeof import('./src/components/ParallaxItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheExpansion: typeof import('./src/components/TheExpansion.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
